project:
  type: website
  output-dir: docs

website:
  title: "Piotr Koc"
  navbar:
    background: "#E5E4E2"
    foreground: "black"
    left:
      - href: index.qmd
        text: Home
      - research.qmd
      - text: "CV"
        href: CV_10_2023_Piotr_Koc.pdf

      
      
format:
  html:
    theme: sandstone
    mainfont: ariel
    fontcolor: "#000000"
    linkcolor: "black"
    css: styles.css
    toc: true
    grid:
      sidebar-width: 50px
      margin-width: 150px
      body-width: 1050px

